version: '3'

networks:
    nginx-php74-mysql8-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql8-service
        networks:
            - nginx-php74-mysql8-node

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        ports:
            - "9000:9000"
        volumes:
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ./app:/var/www/project
            - ./php/logs:/var/log/php
        networks:
            - nginx-php74-mysql8-node

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_DATABASE: database_name
            MYSQL_USER: my_username
            MYSQL_PASSWORD: my_password
            MYSQL_ROOT_PASSWORD: my_password
        networks:
            - nginx-php74-mysql8-node

    # node
    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php74-mysql8-node

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - mysql8-service
        environment:
            PMA_HOST: mysql8-service
            PMA_PORT: 4306
            PMA_ARBITRARY: 1
        restart: always
        ports:
        - 8081:80